### ISSUE TITLE
Main switches to chat

### ISSUE THREAD

**Issue by zany130** [evilphish/sennheiser-gsx-1000#1]
If I select the gsx main 7.1 profile it switches to the chat mono one.
Ubuntu 18.04 Kernal version 4.0

after further testing, I am able to manually change the profile through PulseAudio volume control to the main 7.1 profile but I have to do it for every application I open as the computer will always default to the chat mono profile. I have tried setting the 7.1 main profile to be the default but in PulseAudio volume control but it still defaults to the chat.

**Comment by evilphish** [comment]
You should have two audio sinks in your sound settings that you can switch between without actually touching the profile. Pulseaudio usually remembers the last one that you selected. Can you provide a screenshot of the audio output overview and the output of aplay -l?

**Comment by zany130** [comment]
Here you go. After using it for the day It's not to bad as once I set an application to use the main in PulseAudio volume control it remembers it. I'm just wondering if its possible to have the system default to the main instead of the chat? Like for example steam right now is using the chat profile and if I want it to use the main I have to set it in PulseAudio volume control under playback, is it possible to make it default to main instead? Otherwise, this is really useful and a lot easier than editing the PulseAudio config which seems to break every now and then.

aplay -l
**** List of PLAYBACK Hardware Devices ****
card 0: NVidia [HDA NVidia], device 3: HDMI 0 [HDMI 0]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: NVidia [HDA NVidia], device 7: HDMI 1 [HDMI 1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 0: NVidia [HDA NVidia], device 8: HDMI 2 [HDMI 2]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 0: NVidia [HDA NVidia], device 9: HDMI 3 [HDMI 3]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 1: GSX1000 [GSX 1000 Main Audio], device 0: USB Audio [USB Audio]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 1: GSX1000 [GSX 1000 Main Audio], device 1: USB Audio [USB Audio #1]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 2: Generic [HD-Audio Generic], device 0: ALC1220 Analog [ALC1220 Analog]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: Generic [HD-Audio Generic], device 1: ALC1220 Digital [ALC1220 Digital]
  Subdevices: 0/1
  Subdevice #0: subdevice #0
card 3: Snow [G933 Artemis Spectrum Snow], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0

![image](https://user-images.githubusercontent.com/25832539/50873793-6ce97100-138f-11e9-8ff0-03ff6451e53f.png)

![image](https://user-images.githubusercontent.com/25832539/50873927-10d31c80-1390-11e9-9cbc-53279f6ab9bb.png)

**Comment by evilphish** [comment]
For me it actually defaults to the main unit and not the chat device. I am running Mint 19.1 with the Cinnamon DE. I will take a closer look towards the weekend when I am back home.

**Comment by barskern** [comment]
For me aswell it defaulted to the chat device, but I only needed to swap it to the main unit to get the great sound. Thank you so much for making this @evilphish :smile:
