### ISSUE TITLE
Add support for 2.0 HD audio

### ISSUE THREAD

**Issue by rkmax** [evilphish/sennheiser-gsx-1000#17]
Based on the [Fact sheet](https://assets.sennheiser.com/global-downloads/file/8226/GSX_1000_-_Fact_sheet.pdf ) the card support 96.0 kHz @ 24 bit Output. I really tried to configure this on pulseaudio profiles and paths without success

![Screenshot from 2020-06-30 18-56-46](https://user-images.githubusercontent.com/395707/86188182-71659480-bb03-11ea-8f8d-6d13ff5bb705.png)

**Comment by EnriqueWood** [comment]
You have to configure the daemon.conf file to set the specific default-rate and format to get 2.0HD audio

**Comment by rkmax** [comment]
@EnriqueWood you're right, but I'm looking a way in order to just switch profiles

**Comment by EnriqueWood** [comment]
@rkmax sure, that's the same thing I've been looking for for about two months now and haven't found any satisfactory solutions yet. The closest I have is what I described in the issue I opened in this repository. So if you get further that that, please let me know about it! I still think there must be a way but my understanding of pulseaudio and alsa are very limited.

**Comment by rkmax** [comment]
I spend some time reading the pulseaudio source code and basically using alsa-mixer profiles is not possible. one idea I have and checking if is possible is to have 2 virtual devices using the same card and set different sample rate/format but sounds is like a different setup using [asoundrc](https://www.alsa-project.org/wiki/Asoundrc)

**Comment by EnriqueWood** [comment]
@rkmax please let us know if you could achieve that and what the results were

**Comment by rkmax** [comment]
I did testing by using the .asoundrc config, while I can change to HD audio and back to 7.1 (the indicator in the device is getting updated) using aplay and specifying the device, PulseAudio needs to be restart which is not ideal, I think this is not able to do with the current PulseAudio. i think we can just close this

**Comment by EnriqueWood** [comment]
Before the thread gets closed, could you please share your .asoundrc file here?

**Comment by rkmax** [comment]
For sure, in the `~/.asoundrc` I've added

```
pcm.hd_20 {
  format S24_3LE
  rate 96000
  channels 2
  type hw
  card 3
  device 1
}

pcm.hd_71 {
  format S16_LE
  rate 48000
  channels 8
  type hw
  card 3
  device 1
}

pcm.!default {
  type plug
  slave {
    pcm "hd_20"
  }
}
```

in order to use one or the another I did with the following command.


```
$ aplay -Dplug:hd_20 ~/Downloads/24_bit_fixed_30_dB_atten.wav
```
```
$ aplay -Dplug:hd_71 ~/Downloads/24_bit_fixed_30_dB_atten.wav
```

I get the sample wav files from https://www.sounddevices.com/sample-32-bit-float-and-24-bit-fixed-wav-files/


I get the index card by using `pacmd list-sinks | grep -e 'index:' -e device.string -e 'name: ' -e spec`, may different on each system, the device 1 because I know 0 is the chat output

Here you can see the result https://imgur.com/gallery/d75wv4V, I;m a bad cameraman xD
