### ISSUE TITLE
Mono output always default

### ISSUE THREAD

**Issue by PsychedelicHell** [evilphish/sennheiser-gsx-1000#18]
I just wanted to express my frustration with mono output always being the default when a new application is launched first the first time.

I have to manually open PulseAudio Volume Control and manually select 'GSX 1000 Main Audio main output' over 'GSX 1000 Mono Audio mono output'

This was especially problematic when using Steam Remote Play. 

I was unable to get sound from the client (HTPC) to play as Steam audio was defaulting to the mono output (On my host desktop which has the GSX1000). I was unable to flick it to Main Audio output so I instead went into the sennheiser-gsx-1000.conf and followed the instructions regarding: 

"# If you do not want two devices but only one with a switchable profile"
"# (don't know why you would want that) uncomment the following two"
"# blocks and comment the one block above this comment."

Following this has solved my issue, I no longer have mono output as an option (and it was a nice option for discord) however the trade off of having to always manually switch from mono to 7.1 for every new application was far too annoying.

I also tried the default sink command and it did change the position of the asterisk in the list, but alas new applications would still always default to mono output first.

So while my issue is fixed (I no longer have mono as the default output AND I have sound through Steam Remote Play) I no longer have the separate mono profile as an option in programs like Discord.

I am using Linux Mint 20 Cinnamon.

**Comment by pavelexpertov** [comment]
@PsychedelicHell was `set-default-sink` command available in mint? It's just can't find it in Pop Os 20.04.

**Comment by pavelexpertov** [comment]
Furthermore, have you read this [stackoverflow page](https://askubuntu.com/questions/71863/how-to-change-pulseaudio-sink-with-pacmd-set-default-sink-during-playback#72076)? I am curious to try it, but it's a shame that it's a lot more manual process despite adding the installation scripts.

**Comment by PsychedelicHell** [comment]
> @PsychedelicHell was `set-default-sink` command available in mint? It's just can't find it in Pop Os 20.04.

Yes, I used the command. I could see that it worked, but there was no desired change, mono would still be the default output.

**Comment by evilphish** [comment]
There is a new update that fixes the default to mono by reordering the devices. Please give it a try and if it still does not work feel free to reopen.
