### ISSUE TITLE
GSX 1200 Pro

### ISSUE THREAD

**Issue by ClockWork-abc** [evilphish/sennheiser-gsx-1000#22]
Can't get it to work on Fedora 33. I tried manual install, automatic, a combination of loading the sink manually, etc. 
Unable to use anything else for sound other than the Chat audio.

**Comment by ClockWork-abc** [comment]
I found a solution to get this to work on Fedora 33. For this to work, the device must be 0. I had Device=2,1 and it wasn't working no matter what i tried. After moving my USB to a different port and the device was 0,1 it instantly started working.

**Comment by evilphish** [comment]
Thanks for your update. Closing this
