### ISSUE TITLE
Couple of issues I've noticed attempting this recently

### ISSUE THREAD

**Issue by jp-powers** [evilphish/sennheiser-gsx-1000#26]
I'm running Ubuntu 20.04 and have a Sennheiser GSX 1200 and I've noticed some problems I was able to work around, just wanted to mention them to maybe help.

1. It appears like part of the issue with the GSX1200 and this script may be that firmware updates change the device ID? That's my theory at least, I can't speak to that as fact. I know that I've been able to use this script in the past, and while it required multiple runs and a couple reboots to get it to a "oh, good, it's working" state, I did a firmware update on the GSX1200 and tried it again and it wouldn't work. While poking around I realized that the device ID (product ID, specifically) is incorrect in the provided files. My current device ID is 00a1, the 1200 is thought to be 005f according to the files here, though. This might be the root of the problems, which is why I'm listing it first. A quick `lsusb | grep "Sennheiser"` shows the vendor and device ID, and I'm pretty sure there's a cleaner way to spit out just the needed info.
2. I think this script is trying to do more than is strictly necessary. While figuring out the device ID problem I stumbled on this: https://smartshitter.com/musings/2018/12/sennheiser-gsx-1000-under-linux-take-two/ I ended up going thru both the install.sh and uninstall.sh scripts, deleting anything it touches and rerunning the systemd-hwdb update and udevadm commands just to get to a "clean" state, remade the two files suggested on the linked blog, made the necessary changes for the GSX1200, ran the appropriate udevadm commands... and it just worked.

IF I'm right that the device ID changes, I think it stands to reason that it might be better to generate the files, or at least any that need to explicitly call the device IDs, instead of using pre-fabbed versions.

Edit: also worth noting I guess, some issues others have reported about the speaker output not working are a non-issue for me after doing things this way, so again I imagine it's related to the device ID...

**Comment by EnriqueWood** [comment]
Yeah, I'm having the same problem. In the changelog for the last update they said it will change the device id though.
For GSX-1000 it reports: 
Bus 003 Device 002: ID 1395:00a0 Sennheiser Communications GSX 1000 Main Audio

**Comment by EnriqueWood** [comment]
The solution was even simpler for me, I just changed the` /lib/udev/rules.d/91-pulseaudio-gsx1000.rules` file to update the device id from 005e to 00a0 and reloaded udev rules (or just reboot) and it was working as expected again
