### ISSUE TITLE
PulseAudio defaults to output streams on mono-chat-output

### ISSUE THREAD

**Issue by Chilinot** [evilphish/sennheiser-gsx-1000#3]
This config works great, however whenever i start a new application pulseaudio redirects the audio stream to the mono chat output instead of the main 7.1 output. So i have to manually redirect each stream back to main.

**Comment by Chilinot** [comment]
For some reason, swapping the priorities of the two sinks, main becoming 1, and chat becoming 2, seems to have fixed the issue for me. Is it not supposed to prioritize the sink with the highest priority?

**Comment by Chilinot** [comment]
I should probably note my system:
OS: Fedora 29
Kernel: 5.1.11
PulseAudio: 12.2-rebootstrapped

**Comment by evilphish** [comment]
I have tried looking for information on how the priority setting actually works. From the documentation it says that the one with "higher priority" is used first which - looking at the issue and your fix - seems slightly vague. Does anyone have any resource which actually states whether lower or higher values have higher priority for the pulseaudio setting?

**Comment by Chilinot** [comment]
That is what i have found as well. What is even more wierd is that with my "fix", attempting to change the volume using my keyboard media buttons changes the mono-output instead. Pulseaudio seems to assume the mono-audio is the defualt, but outputs all sound on my 7.1 output.

Going in and manually changing the default to the 7.1 sink fixes the keyboard issue, as well as retain all output on the 7.1 sink. Pulseaudio is wierd.

**Comment by evilphish** [comment]
Is this still an issue with you? I am at a loss as to where to look for further details. If your workaround works for you we could close this and agree that pulseaudio is weird ;)

**Comment by Chilinot** [comment]
I still have this issue and my "workaround" seems to work. I have also not had any success in finding the root cause for this. The documentation for the pulseaudio configuration file is a bit lacking. Im closing this since it is most likely an issue with pulseaudio.

**Comment by evilphish** [comment]
Changed the readme to reflect on how to set the default sink for pulseaudio in general. Feel free to check it out.
