### ISSUE TITLE
Getting Mono sound only.

### ISSUE THREAD

**Issue by PsychedelicHell** [evilphish/sennheiser-gsx-1000#30]
I have built a new machine and installed a fresh copy of Linux Mint, I've previously had the DAC working perfectly but now I only get mono sound (a problem I've faced previously but my old solutions are not working).

I've tried to run both the installer and the manual method, with multiple restarts and both installation methods give me mono sound output only. When in the sound settings I see the following.
![image](https://user-images.githubusercontent.com/57477439/118385705-a6fc6900-b654-11eb-8c4b-ebccbd7f6433.png)
When I go to 'Test sound' I don't see any speaker options:
![image](https://user-images.githubusercontent.com/57477439/118385740-05294c00-b655-11eb-9e1d-8c9bf9b7553e.png)
Although 'Multichannel' is selected, the sound coming out of my headphones is mono and switching to speakers on the DAC directly doesn't work, no sound is pushed to external speakers at all.

This is so frustrating, especially since I had it working on my old machine and the DAC is working perfectly fine in Windows.

Has anyone else had this issue and found a solution?

EDIT:
I've found a 'dirty' fix which was the following.

In the file: `/usr/share/pulseaudio/alsa-mixer/profile-sets/sennheiser-gsx-1000.conf:` I changed the channel map under '[Mapping analog-output-chat]' from 'mono' to 'channel-map = front-left,front-right,front-center,lfe,rear-left,rear-right,side-left,side-right' and now I have working 7.1 sound.
![image](https://user-images.githubusercontent.com/57477439/118386291-cf3a9680-b659-11eb-91ac-c49c93bc0c0d.png)

I'm not a coder by any means so I do not really understand what I am doing or what is going on. But I wanted to test a few things out to maybe help those of you in this Github. I went and changed the name of the 'main output' by putting my username inside. After running a quick `pulseaudio -k` saw the name change appear in the sound settings:
![image](https://user-images.githubusercontent.com/57477439/118386282-bf22b700-b659-11eb-8efe-627ffa24476c.png)

I thought this was weird because my change to get the 7.1 sound was done on the 'mono' profile below the profile of the output with the name change.
![image](https://user-images.githubusercontent.com/57477439/118386359-48d28480-b65a-11eb-856b-e2538f046885.png)

If anyone wants to do some further investigation with me, please let me know! I'm curious as to why this was happening and maybe we can push a new update that will take this phenomena into account and make the automatic installer work properly.

**Comment by cactushydrocodone** [comment]
Same, mono sound is only on the right. I cant deal with this.
My temporary fix is setting the default sink to the surround device every login. 
As i use pipewire, somehow i need to start pavucontrol once to actually apply the changes on login.

To fix this, i just removed the monodevice entirely. I dont use it anyway.

**Comment by thorsten-passfeld** [comment]
Does anyone have a proper solution yet? I mean the Pulseaudio team can't just claim that the GSX 1000 works when this is what we have to deal with. I also still use my bandaid solution for setting the default sink.

**Comment by cactushydrocodone** [comment]
my workaround:
in `~/.config/pipewire/media-session.d/default-profile`:
```
{
 "default.profile.alsa_card.usb-Sennheiser_GSX_1000_Main_Audio_<somenumberidontwanttoshare>-00": { "name": "output:analog-output-surround71+output:analog-output-chat+input:analog-input" }
}
```

in `~/.config/pipewire/media-session.d/default-routes`:
```
{
 "default.route.alsa_card.usb-Sennheiser_GSX_1000_Main_Audio_<somenumberidontwanttoshare>-00:profile:off": [ ],
 "default.route.alsa_card.usb-Sennheiser_GSX_1000_Main_Audio_<somenumberidontwanttoshare>-00:profile:output:mono-fallback+input:mono-fallback": [ ],
}
```

The only thing needed to "activate" this is to open pavucontrol one time when starting *any* application that does voice chat and is electron-like.

Oh: And DO NOT upgrade *any* pipewire packages on archlinux to any version after `1:0.3.40-1`. Any version after that does NOT work with the GSX. If already upgraded, downgrade. Theres no other way (yet).

Update: The stable pipewire packages are still broken. Update to the git ones, downgrading is no longer neccessary. Chaotic AUR has them precompiled in their repositories (If arch).

**Comment by evilphish** [comment]
Solution in most recent packages
