### ISSUE TITLE
New PulseAudio update -- Benefits and/or downsides for this project?

### ISSUE THREAD

**Issue by pavelexpertov** [evilphish/sennheiser-gsx-1000#32]
I've randomly stumbled upon a [release information page](https://www.freedesktop.org/wiki/Software/PulseAudio/Notes/15.0/#sennheisergsx10001200pro) for pulse audio and there's a section for the Sennheiser deck.

@evilphish, what do you think it will mean for your scripts?

**Comment by evilphish** [comment]
Well, hopefully everything then works out of the box and my scripts will be obsolete ;)
Let's wait and see

**Comment by pavelexpertov** [comment]
Cool! Let's wait and see.
