### ISSUE TITLE
Only getting one output device

### ISSUE THREAD

**Issue by OnlyBjarne** [evilphish/sennheiser-gsx-1000#4]
just tried to install my gsx 1000 on manjaro, but i only get one audio device (mono chat), both devices are listed as devices in `aplay -l, any help would be helpfull!

**Comment by evilphish** [comment]
Did you try removing it and using the install script that just got committed? Might be worth giving this a try.

**Comment by OnlyBjarne** [comment]
Doesn't seem like the install-script made any difference. Do i need to add the sinks in pulseaudio's default.pa?

**Comment by jataro** [comment]
@OnlyBjarne I had the same problem and found that the following conf worked well. 
Copied from this bug report.  https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1821494
```
[General]
auto-profiles = yes

[Mapping analog-mono]
device-strings = hw:%f,0,0
channel-map = mono

[Mapping analog-surround-71]
device-strings = hw:%f,1,0
channel-map = front-left,front-right,front-center,lfe,rear-left,rear-right,side-left,side-right
direction = output

[Profile output:analag-mono+output:analog-surround-71+input:analog-mono]
output-mappings = analog-mono analog-surround-71
input-mappings = analog-mono
priority = 5100
skip-probe = yes
```

**Comment by OnlyBjarne** [comment]
I also that profile, but I still only get main audio analog mono as output device. the profile seems to load fine, but i cant choose the output device i want
![Screenshot_20190907_160527](https://user-images.githubusercontent.com/10653383/64475942-6531d480-d189-11e9-8475-7c1a90fabbf4.png)
![Screenshot_20190907_160618](https://user-images.githubusercontent.com/10653383/64475946-71b62d00-d189-11e9-8971-17ad945b7a15.png)

**Comment by jonseppanen** [comment]
Getting this issue as well on latest manjaro. I have previously used this repo before without issue on like, 4 different installs. Perhaps something has changed in pulseaudio?

**Comment by jonseppanen** [comment]
Further to my comment, seems to be something wrong with the udev/env var. Hard coding it to the card number works fine.

**Comment by zany130** [comment]
I am also having this issue on ubuntu 18.04

**Comment by evilphish** [comment]
Everything working fine here with Mint 19.3 and cinnamon DE. I also recently modified the readme to reflect setting the default sink. You might also give that a try.

**Comment by zany130** [comment]
I no longer have the gsx 1000 so, unfortunately, I won't be able to test

**Comment by evilphish** [comment]
Ok thank you. Closing for now. If someone else has this issue and is able to test please reopen.
