### ISSUE TITLE
sound is muted when opening pavucontrol when attached to USB-dock

### ISSUE THREAD

**Issue by hartmark** [evilphish/sennheiser-gsx-1000#6]
Firstly I want to thank for this awesome workaround to get our device working perfectly in linux.

I have no problems if I connect my GSX 1000 directly into my computer, but when I connect it to a USB-hub I get that my sound is muted when opening pavucontrol, and when closing it the sound resumes.

Do you have any theories?

I'm on arch linux.

**Comment by evilphish** [comment]
I have a USB 3.1 Hub here but things work flawlessly with it. Mint 19.2 here.

**Comment by hartmark** [comment]
This must have been something that have been fixed in updated system as I cannot replicate the bug anymore.
