### ISSUE TITLE
GSX1200 Speaker output stopped working

### ISSUE THREAD

**Issue by breakfixrepeat** [evilphish/sennheiser-gsx-1000#8]
Firstly, great work in getting the GSX hardware working in linux.

I've installed this in Fedora 31 and initially it was working beautifully with my default speaker preset and could change the audio settings using the hardware controls. When I switched to my headphone preset for a short period and tried to switch back to the speaker preset it has now stopped working for the speaker output entirely.

Headphones still work fine but whenever I switch to speakers I get no audio output, any ideas?

Edit: Oddly if I select the GSX 1200 as the output source in Discord with speakers enabled I get an audio cue, still no change in other applications though. Pavucontrol audio slider also produces output through the speakers.

**Comment by evilphish** [comment]
Hey, sorry for the late reply. Unfortunately I have no clue about the specifics in Fedora. With Mint 19.3 it just works. Have you tried reinstalling? Maybe an update of yours broke some pulseaudio or udev configs?

**Comment by breakfixrepeat** [comment]
After further experimentation on both Fedora 31 & Ubuntu 18.04 it appears to have something to do with my setup, with the GSX 1200 not being directly connected to my computer, but rather a USB hub/switch.

If I use the gnome sound settings to test the output of the main output it's stuck on mono output (with no sound from the speakers, only headset - all despite showing 7.1 as the profile) and with pavucontrol open to the side shows the audio output coming from the chat output. Seems to be a conflict/mixup between the two devices.

I've tried switching the devices around in your alsa-mixer config but that results in the device disappearing altogether.

aplay -l output:
```
card 2: GSX1200 [GSX 1200 Pro Main Audio], device 0: USB Audio [USB Audio]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
card 2: GSX1200 [GSX 1200 Pro Main Audio], device 1: USB Audio [USB Audio #1]
  Subdevices: 1/1
  Subdevice #0: subdevice #0
```

**Comment by breakfixrepeat** [comment]
It's suddenly started working on both Fedora & Ubuntu, only the Main audio output is available but I can switch between profiles on the DAC and everything just works. I wander if there's been an update to pulse audio that fixed the issues I was having.
