### ISSUE TITLE
Channel output problems

### ISSUE THREAD

**Issue by PsychedelicHell** [evilphish/sennheiser-gsx-1000#9]
Firstly, congratulations on getting this software to _mostly_ work with Linux.

**My testing**
I am unable to get the software working GNOME, I tried using the latest release of Manjaro GNOME and Pop!_OS. Using both the install.sh method as well as manually copying the files.

I got the software working under Manjaro KDE via the install.sh method followed by a system reboot. I saw that there was the option of 7.1 surround in the sound settings.

**Results**
After selecting the settings I tried each channel these were my results with both stereo headphones and stereo speakers.

**Front left, front right, side left, side right:** Work perfectly.
**Rear left and rear right:** Both play out of both speakers simultaneously.
**Center:** Plays out of the left speaker.
**Subwoofer:** plays out of the right speaker.

**Summary**
So while it is working, it's not quite right, especially for those after positional audio in games and leaves some other things sounding funny. Especially videos where center sound is only heard in my left hear and bass is heard only in my right.

Keep working at it! Would be amazing if this unit could run as good on Linux as it does on Windows.

**Additional**
Again I could not get this working on GNOME, only Arch Linux. Specifically, Manjaro KDE Plasma 5.17.5 running Kernel 5.4.23-1

**Comment by evilphish** [comment]
Hey, thanks for your input. I am using Linux Mint 19.3 with Cinnamon as my DE and here it works quite nicely. 
- If I test for the rear speakers the difference in direction is very slight but noticable
- Center works fine, playing on both speakers
- Front left and right are also noticable in the corresponding direction and quite pronounced
- Left and right work perfectly only on the corresponding side

 Maybe this is also connected to the headset you are using?

**Comment by PsychedelicHell** [comment]
Thanks for your response!

Interesting that your channel mixing is fine.

I'm using the Sennheiser GSP 600 as my headphones and the Edifier R1850DB as my speakers.

Both of outputs have the channel mixing issues, most notebly with Centre coming from the left and Sub coming from the right.

I doubt it's my hardware, all this equipment is new and it does not have the channel mixing issues under Windows. 

I will try Linus Mint and get back to you on whether it solves the mixing issue for me.

**Comment by evilphish** [comment]
I am using a Beyerdynamics MMX300 headset. Give me a shout once you tried Mint.

**Comment by PsychedelicHell** [comment]
So I've got Linux Mint installed, I ran the install.sh and besides getting the "[pulseaudio] main.c: Daemon startup failed." message at the end it all copied to the correct folders.

![image](https://user-images.githubusercontent.com/57477439/78209650-5333cc80-74f3-11ea-9fc2-4de7f282a522.png)

When opening sound I can select the 7.1 surround output profile but when I click on 'test sound' there are no channels for me to pick. 

I do have sound when I play music and videos in the browser; that's working fine through the headphones but I want to be able to test the individual channels in the system settings to be 100% sure they're all mixing properly.

![image](https://user-images.githubusercontent.com/57477439/78209471-d56fc100-74f2-11ea-801d-8a0d8ec7f339.png)

Do you have the same thing in the screenshot I've provided or is your 'test sound' section populated with the respective speakers?

**Comment by evilphish** [comment]
I had the same result at first but after closing the window and opening it again test sound produced a window with the correct testing buttons. Sometimes it also helps to run pavucontrol in between which is super weird but I have not yet figured out why that is.

**Comment by PsychedelicHell** [comment]
Opening and closing the window didn't make anything appear, what are the terminal commands for this pavucontrol solution?

**Comment by evilphish** [comment]
Just execute pavucontrol. You might have to install it first. On Mint or any other Debian derivative
`apt-get install pavucontrol`
should suffice.

**Comment by evilphish** [comment]
I just replicated the issue again. Open up pavucontrol and set the Main Audio as the fallback device (there is a small button to the right of the volume slider in the output tab). For whatever reason after a reboot the chat audio gets set as fallback.

Anyways after selecting main audio as fallback the sound testing buttons for the different channels are back :)

**Comment by PsychedelicHell** [comment]
Your steps worked; I managed to get the 'test sound' up and working after installing pavucontrol (need to use sudo). I then flicked the 'fallback device' as you said and then the icons appeared in test sound.

**Testing:**

Unfortunately I can still very much hear the "centre" and "subwoofer channels in the left and right speakers, the same experience I had on Manjaro KDE.

**Problems that still persist:**

1) Rear right is much louder than rear left.
2) It's very subtle but front center still sounds like its coming more from the left side than evenly in the middle.
3) Similar to the center experience being louder in the left speaker, the Subwoofer sounds louder coming from the right speaker.

_The only speakers that sound correct are the front & sides for left and right._

**Final thoughts:**
I do not have any of these channel issues in Windows, the DAC works perfectly there.

Perhaps it is just a limitation with ALSA, hopefully someone comes along and fixes the channels as this is really the only thing holding me back from enjoying Linux.

**Comment by evilphish** [comment]
I also modified the readme to reflect automatically setting the default sink (No need for pavucontrol anymore). 
Could your problem maybe also be related to this: https://bugs.launchpad.net/ubuntu/+source/pulseaudio/+bug/1821494 ?

**Comment by PsychedelicHell** [comment]
That bug report looks like what I'm experiencing, it looks like it's over a year old. Has a solution been made or is this still broken?

**Comment by evilphish** [comment]
I guess it is still open and the OP attached a config file that you might be able to make work. It is basically the config from this repo but with some other options. I am not quite clear what he did differently that would solve that issue. The config is almost the same as mine. He uses auto-profiles yes which is notorious for creating problems with PA generating default profiles and activating them instead of the custom one, hence why I have set it to no.

I guess the magic might be in the channel mapping. You can try changing the positions of these values till it sounds the way you want it. Still leaves me puzzled as to why me and many others do not suffer from this problem albeit using the same config file.....

**Comment by Oro** [comment]
I am also experiencing an incorrect channel assignment (same as this issue, center is on the left, rear on both) with a GSX1200 and a Beyerdynamic DT 990
Both of you are using a GSX1200? Maybe the channel assignments differ between GSX1000 and GSX1200?
In any case, changing the channel map via

```diff
diff --git a/usr/share/pulseaudio/alsa-mixer/profile-sets/sennheiser-gsx-1200.conf b/usr/share/pulseaudio/alsa-mixer/profile-sets/sennheiser-gsx-1200.conf
index 6cade17..b2c015d 100644
--- a/usr/share/pulseaudio/alsa-mixer/profile-sets/sennheiser-gsx-1200.conf
+++ b/usr/share/pulseaudio/alsa-mixer/profile-sets/sennheiser-gsx-1200.conf
@@ -37,7 +37,7 @@ auto-profiles = no
 description = main output
 device-strings = hw:CARD=GSX1200,DEV=1
 #device-strings = hw:%f,1
-channel-map = front-left,front-right,rear-left,rear-right,front-center,lfe,side-left,side-right
+channel-map = front-left,front-right,front-center,lfe,rear-left,rear-right,side-left,side-right
 paths-output = analog-output analog-output-lineout analog-output-speaker
 priority = 2
```
 corrects the output channels for me (tested via `speaker-test -c 8` and Tomb Raider)

**Comment by PsychedelicHell** [comment]
Hey Oro,

I am lost with where to begin with your post, could you please provide step by step instructions with what I'm supposed to do? 

When I add your lines into the .conf file:

![image](https://user-images.githubusercontent.com/57477439/80270068-643dbb00-86f8-11ea-8186-a1af033a565e.png)

Then reboot, the GSX is completely gone from the system audio options:

![image](https://user-images.githubusercontent.com/57477439/80270033-293b8780-86f8-11ea-8988-081ecf5d837c.png)

I am using Manjaro KDE & the GSX1000 and a massive Linux noob.

**EDIT: I figured it out!**

So there was a misunderstanding with how I was reading your code. I copy pasted it all in the conf when all I needed to do was remove line 40 from Evilphish's .conf which was:
-channel-map = front-left,front-right,rear-left,rear-right,front-center,lfe,side-left,side-right
and replace it with Oro's which is:
+channel-map = front-left,front-right,front-center,lfe,rear-left,rear-right,side-left,side-right

I now have all the channels working perfectly! **Thank you Evilphish and Oro!**

To anyone else out there experiencing the output channel problems, make sure your sennheiser-gsx-1000.conf looks like this:

![image](https://user-images.githubusercontent.com/57477439/80270285-ed092680-86f9-11ea-8fa6-4ff0d4c3edfc.png)

**Comment by EugenMayer** [comment]
I fixed a couple of issues in #10 including this one.

Since we seem to have different experiences and we do not now why, i left it as a question during the installation ( if to install the channel-swap fix or not ). I treat the "normal channel mix" as being the current version and the channel-swap being https://github.com/evilphish/sennheiser-gsx-1000/issues/9#issuecomment-619147998

For me, there is no doubt that the channels are swapped. Center is lefty, Sub is righty (def objective) and i even would tell that with the channel-swap right / left back are far more clear to place too ( maybe subjective ).

Until we better know why we have different results i suggest "asking during the installation" is our best bet.

**Comment by evilphish** [comment]
Are you guys with the channel swap problems all using the 1200s? I am using the 1000 and never had any channel swap issue. As Oro pointed out, maybe there is a difference in channel assignments between the devices?

**Comment by EugenMayer** [comment]
Using a 1000 too with yet HyperX Cloud Alpha, can try with M40X tomorrow.

Are you guys using a cable to split out/in  (4wire cable) to feed it into your 1000? If yes, which standard?

Is there anybody having this issue and direcly feeding Headphones without any adapters in between, and if yes, do you need a channel swap or not?

**Comment by PsychedelicHell** [comment]
@evilphish I am using the GSX1000 and had the channel swap issue, I don't think it's restricted to the GSX1200. My headphones are the Sennheiser GSP 600.

My problem as described by @EugenMayer was fixed with the channel swap solution from @Oro
